spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username:
    password:
    driver-class-name: org.h2.Driver

    # web 요청이 왔을 때 페이지가 1부터 시작
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

